### ISSUE TITLE
Update deployment workflow

### ISSUE THREAD

**Issue by LanceJernigan** [thinkpyxl/outset#13]
We need to update the circle ci config file to match the new deploy patterns

**Comment by LanceJernigan** [comment]
```
workflows:
  version: 2
  deploy:
    jobs:
      - prod:
          filters:
            branches:
              only:
                - master
      - stag:
          filters:
            branches:
              only:
                - /release/.*/
      - dev:
          filters:
            branches:
              only:
                - /bug/.*/
                - /feature/.*/

```
