### ISSUE TITLE
Cache dependencies between builds

### ISSUE THREAD

**Issue by LanceJernigan** [thinkpyxl/outset#14]
We can utilize caches to speed up node_modules and composer installs.  Below is an example snippet to implement in the circleci config

```
- save_cache:
      key: node_modules-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
```
